version: '3'
services:
  web:
    build: .
    volumes:
      - "./:/recurring"
    ports:
      - 3000:3000
    env_file: ".env"
    command: "bundle exec rails s -b '0.0.0.0'"
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    image: postgres:9.4
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
