default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recurring_development

test:
  <<: *default
  database: recurring_test

